# Generated by Django 2.2.5 on 2019-10-15 15:13

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_grapesjs.models.base
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrapesJSJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
                ('gjs_assets', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('gjs_css', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('gjs_styles', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('gjs_html', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('gjs_components', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grapes model',
                'verbose_name_plural': 'grapesjs models',
            },
            bases=(django_grapesjs.models.base.ModelToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GrapesJSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
    ]
